package com.baidu.beidou.tool.bo;

import java.util.Date;

/**
 * UserSnapshotFile generated by MyEclipse Persistence Tools
 */

public class SnapShotFile implements java.io.Serializable {

	// Fields

	private Integer id;
	private SnapShot userSnapshot;
	private Integer userid;
	private String fileName;
	private Integer size;
	private Date createtime;
	private Byte isEmailed;
	private Date emailTime;
	private String token;
	private Date tokenCreateTime;
	private Integer allowDownTimes;
	private Date lastDownloadTime;
	private Date deleteTime;
	private String snapDomain;

	// Constructors

	public String getSnapDomain() {
		return snapDomain;
	}

	public void setSnapDomain(String snapDomain) {
		this.snapDomain = snapDomain;
	}

	/** default constructor */
	public SnapShotFile() {
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SnapShot getUserSnapshot() {
		return this.userSnapshot;
	}

	public void setUserSnapshot(SnapShot userSnapshot) {
		this.userSnapshot = userSnapshot;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Byte getIsEmailed() {
		return this.isEmailed;
	}

	public void setIsEmailed(Byte isEmailed) {
		this.isEmailed = isEmailed;
	}

	public Date getEmailTime() {
		return this.emailTime;
	}

	public void setEmailTime(Date emailTime) {
		this.emailTime = emailTime;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getTokenCreateTime() {
		return this.tokenCreateTime;
	}

	public void setTokenCreateTime(Date tokenCreateTime) {
		this.tokenCreateTime = tokenCreateTime;
	}

	public Integer getAllowDownTimes() {
		return this.allowDownTimes;
	}

	public void setAllowDownTimes(Integer allowDownTimes) {
		this.allowDownTimes = allowDownTimes;
	}

	public Date getLastDownloadTime() {
		return this.lastDownloadTime;
	}

	public void setLastDownloadTime(Date lastDownloadTime) {
		this.lastDownloadTime = lastDownloadTime;
	}

	public Date getDeleteTime() {
		return this.deleteTime;
	}

	public void setDeleteTime(Date deleteTime) {
		this.deleteTime = deleteTime;
	}

}