package com.baidu.beidou.tool.bo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserSnapshot generated by MyEclipse Persistence Tools
 */

public class SnapShot implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer userid;
	private Integer status;
	private Integer planid;
	private Integer groupid;
	private Integer sitetype;
	private String site;
	private String email;
	private Date addtime;
	private Integer adduser;
	private Integer priority;
	private SnapShotFile file;

	// Constructors

	/** default constructor */
	public SnapShot() {
	}

	/** minimal constructor */
	public SnapShot(Integer userid, Integer status, Integer planid,
			Integer groupid, Integer sitetype, String email, Date addtime,
			Integer adduser, Integer priority) {
		this.userid = userid;
		this.status = status;
		this.planid = planid;
		this.groupid = groupid;
		this.sitetype = sitetype;
		this.email = email;
		this.addtime = addtime;
		this.adduser = adduser;
		this.priority = priority;
	}


	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getPlanid() {
		return this.planid;
	}

	public void setPlanid(Integer planid) {
		this.planid = planid;
	}

	public Integer getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	public Integer getSitetype() {
		return this.sitetype;
	}

	public void setSitetype(Integer sitetype) {
		this.sitetype = sitetype;
	}

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Integer getAdduser() {
		return this.adduser;
	}

	public void setAdduser(Integer adduser) {
		this.adduser = adduser;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public SnapShotFile getFile() {
		return file;
	}

	public void setFile(SnapShotFile file) {
		this.file = file;
	}

}