package com.baidu.beidou.cproplan.bo;

// Generated 2008-7-19 14:42:33 by Hibernate Tools 3.2.1.GA


/**
 * CproPlan generated by hbm2java
 */
public class CproPlan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6615023925930181201L;

	private Integer planId;

	private Integer planState;
	
	private Integer userId;
	
	private String planName;
	
	public Integer getPlanId() {
		return this.planId;
	}

	public void setPlanId(Integer planId) {
		this.planId = planId;
	}

	public Integer getPlanState() {
		return this.planState;
	}

	public void setPlanState(Integer planState) {
		this.planState = planState;
	}	
	
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}	

	public String getPlanName() {
		return planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [");
		buffer.append("planId").append("='").append(getPlanId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other)){
			return true;
		}
		if ((other == null)){
			return false;
		}
		if (!(other instanceof CproPlan)){
			return false;
		}
		CproPlan castOther = (CproPlan) other;

		return ((this.getPlanId() == castOther.getPlanId()) || (this
				.getPlanId() != null
				&& castOther.getPlanId() != null && this.getPlanId().equals(
				castOther.getPlanId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPlanId() == null ? 0 : this.getPlanId().hashCode());

		return result;
	}
}