package com.baidu.beidou.cprogroup.bo;

// Generated 2008-7-19 14:42:33 by Hibernate Tools 3.2.1.GA

/**
 * CproPlan generated by hbm2java
 */
public class CproGroup implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4734031663571012306L;

	private Integer groupId;

	private String siteList;

	private String siteTradeList;

	private int userId;

	public String toString() {
		return "groupId=" + groupId + ", siteList='" + siteList + "',siteTradeList='" + siteTradeList + "'";
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getSiteList() {
		return siteList;
	}

	public void setSiteList(String siteList) {
		this.siteList = siteList;
	}

	public String getSiteTradeList() {
		return siteTradeList;
	}

	public void setSiteTradeList(String siteTradeList) {
		this.siteTradeList = siteTradeList;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}