package com.baidu.beidou.cprogroup.bo;

// Generated 2009-6-25 10:28:06 by Hibernate Tools 3.2.1.GA


/**
 * Keyword0 generated by hbm2java
 */
public class CproKeyword implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String keyword;
	private Long wordId;
	private Integer groupId;
	private Integer planId;
	private Integer userId;
	
	public String getKeyword() {
		return keyword;
	}
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}
	public Long getWordId() {
		return wordId;
	}
	public void setWordId(Long wordId) {
		this.wordId = wordId;
	}
	public Integer getGroupId() {
		return groupId;
	}
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}
	public Integer getPlanId() {
		return planId;
	}
	public void setPlanId(Integer planId) {
		this.planId = planId;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	
	
}
