package com.baidu.beidou.cprogroup.bo;

// Generated 2009-3-13 19:20:52 by Hibernate Tools 3.2.1.GA

/**
 * GroupSitePrice generated by hbm2java
 */
public class GroupSitePrice implements java.io.Serializable {

	private Integer siteid;
	private String siteurl;
	private Integer price;
	private String targeturl;
	
	public Integer getPrice() {
		return price;
	}
	public void setPrice(Integer price) {
		this.price = price;
	}
	public Integer getSiteid() {
		return siteid;
	}
	public void setSiteid(Integer siteid) {
		this.siteid = siteid;
	}
	public String getSiteurl() {
		return siteurl;
	}
	public void setSiteurl(String siteurl) {
		this.siteurl = siteurl;
	}
	public String getTargeturl() {
		return targeturl;
	}
	public void setTargeturl(String targeturl) {
		this.targeturl = targeturl;
	}
}