package com.baidu.beidou.cprogroup.bo;

// Generated 2009-3-13 19:20:52 by Hibernate Tools 3.2.1.GA

/**
 * GroupSiteFilter generated by hbm2java
 */
public class GroupSiteFilter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8151231955231658750L;

	private String site;

	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}
}
