package com.baidu.beidou.cprogroup.bo;

// Generated 2009-3-13 19:20:52 by Hibernate Tools 3.2.1.GA

/**
 * GroupIpFilter generated by hbm2java
 */
public class GroupIpFilter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -87320380042801154L;

	private String ip;

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
}
