package com.baidu.beidou.cprogroup.bo;

// Generated 2008-7-19 14:42:33 by Hibernate Tools 3.2.1.GA


/**
 * CproPlan generated by hbm2java
 */
public class SiteInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6615023925930181201L;

	private Integer siteId;

	private Integer firstTradeId;
	
	private Integer secondTradeIid;

	/**
	 * @return the firstTradeId
	 */
	public Integer getFirstTradeId() {
		return firstTradeId;
	}

	/**
	 * @param firstTradeId the firstTradeId to set
	 */
	public void setFirstTradeId(Integer firstTradeId) {
		this.firstTradeId = firstTradeId;
	}

	/**
	 * @return the secondTradeIid
	 */
	public Integer getSecondTradeIid() {
		return secondTradeIid;
	}

	/**
	 * @param secondTradeIid the secondTradeIid to set
	 */
	public void setSecondTradeIid(Integer secondTradeIid) {
		this.secondTradeIid = secondTradeIid;
	}

	/**
	 * @return the siteId
	 */
	public Integer getSiteId() {
		return siteId;
	}

	/**
	 * @param siteId the siteId to set
	 */
	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}
}